# .github/workflows/ci.yml
name: ci

on: [push, pull_request]

jobs:
  ci:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@64-fix-phpdoc-checks
    #secrets:
      # Required if you plan to publish (uncomment the below)
      # moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
    with:
      internal_workflow_branch: '64-fix-phpdoc-checks'
      codechecker_max_warnings: 0 # CI should now fail on phpcs / code checker warnings.
      disable_behat: true
      disable_grunt: true
      extra_plugin_runners: |
          moodle-plugin-ci add-plugin catalyst/moodle-local_aws --branch ci-for-tool_dataflows;
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y graphviz;
